FROM node:latest

WORKDIR /app

# Installing the dependencies
COPY ../../src/frontend/package*.json ./
RUN npm ci

# Copying source code files
COPY ../../src/frontend /app

# Building the application
RUN npm run build

EXPOSE 5173     

CMD ["npm", "run", "dev"]