FROM node:latest

WORKDIR /app

# Installing the dependencies
COPY ../../src/frontend/pnpm-lock.yaml ../../src/frontend/package*.json ./

RUN npm install -g pnpm

RUN pnpm i

COPY ../../src/frontend .


# Building the application
RUN pnpm run build

EXPOSE 5173     

CMD ["pnpm", "run", "dev"]