apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "titeenipeli.name" . }}-cert
  labels: 
    {{- include "titeenipeli.labels" . | nindent 4 }}
spec:
  secretName: {{ include "titeenipeli.name" . }}-cert
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048 
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "{{ .Values.hostedZoneName }}"
  dnsNames:
    - "{{ .Values.hostedZoneName }}"
    - "*.{{ .Values.hostedZoneName }}"  
