apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "titeenipeli.name" . }}-config
  labels:
    {{- include "titeenipeli.labels" . | nindent 4 }}
data:
  appsettings.json: |
    {{- .Files.Get "files/appsettings.json" | nindent 4 }}
