apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "titeenipeli.frontendName" . }}
  labels:
    {{- include "titeenipeli.frontendLabels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "titeenipeli.frontendSelectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "titeenipeli.frontendSelectorLabels" . | indent 8 }}
    spec:
      containers:
        - image: titeenipelitacr.azurecr.io/frontend:latest
          name: frontend
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "titeenipeli.backendName" . }}
  labels:
    {{- include "titeenipeli.backendLabels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "titeenipeli.backendSelectorLabels" . | indent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "titeenipeli.backendLabels" . | indent 8 }}
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_HTTPS_PORTS
              value: "443"
            - name: ASPNETCORE_HTTP_PORTS
              value: "80"
            - name: ASPNETCORE_Kestrel__Certificates__Default__Password
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: /https/aspnetapp.pfx
            - name: Bot__Token
            - name: JWT__Encryption
            - name: JWT__Secret
            - name: DB_NAME
              value: {{ .Values.databaseName }}
            - name: DB_USERNAME
              value: {{ .Values.databaseUserName }}
            - name: SQLCONNSTR_Database
              value: Server=db;Port=5432;Userid=$(DB_USERNAME);Timeout=15;Database=$(DB_USERNAME);Password=$(SECRET_PART1);
          image: titeenipelitacr.azurecr.io/backend:latest
          name: backend
          volumeMounts:
            - mountPath: /https
              name: cert
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: cert
          persistentVolumeClaim:
            claimName: cert
            readOnly: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "titeenipeli.botName" . }}
  labels:
    {{- include "titeenipeli.botLabels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "titeenipeli.botSelectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "titeenipeli.botLabels" . | indent 8 }}
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: Backend__AuthorizationHeaderName
              value: X-BOT-KEY
            - name: Backend__BackendUrl
              value: http://proxy
            - name: Backend__FrontendUrl
              value: http://localhost:8080
            - name: Backend__Token
            - name: Telegram__Token
          image: titeenipelitacr.azurecr.io/bot:latest
          name: bot
      restartPolicy: Always
