apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "titeenipeli.name" . }}-cluster
  labels: {{- include "titeenipeli.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  primaryUpdateStrategy: unsupervised
  monitoring:
    enablePodMonitor: true
  storage:
    size: 10Gi
    #storageClass: ultra-disk-sc
  managed:
    roles:
    - name: app
      createdb: true
      login: true
  enableSuperuserAccess: true
  postgresql:
    parameters:
      shared_buffers: "512MB"
      max_connections: "1000"
      log_min_duration_statement: "3500"
      "pgaudit.log": "all, -misc"
      "pgaudit.log_catalog": "off"
      "pgaudit.log_parameter": "on"
      "pgaudit.log_relation": "on"


  # TODO: backup to cloud
