apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "titeenipeli.name" . }}-cluster
  labels: {{- include "titeenipeli.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  primaryUpdateStrategy: unsupervised
  monitoring:
    enablePodMonitor: true
  storage:
    size: 10Gi
  managed:
    roles:
    - name: app
      createdb: true
      login: true
  enableSuperuserAccess: true
  postgresql:
    parameters:
      shared_buffers: "512MB"
      max_connections: "1000"
      log_min_duration_statement: "3500"
  backup:
    barmanObjectStore:
      destinationPath: {{ .Values.dbBackupContainer }}
      azureCredentials:
        inheritFromAzureAD: true
  serviceAccountTemplate:
    metadata:
      annotations:
        azure.workload.identity/client-id: {{ .Values.clientId }}
      labels:
        azure.workload.identity/use: "true"

---

apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: {{ include "titeenipeli.name" . }}-cluster-final
  labels: {{- include "titeenipeli.labels" . | nindent 4 }}
spec:
  cluster:
    name: {{ include "titeenipeli.name" . }}-cluster
