apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "titeenipeli.name" . }}-cluster
  labels: {{- include "titeenipeli.labels" . | indent 4 }}
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  primaryUpdateStrategy: unsupervised
  monitoring:
    enablePodMonitor: true
  storage:
    size: 10Gi
  enableSuperuserAccess: true
  postgresql:
    parameters:
      shared_buffers: "256MB"
      max_connections: "100"
  bootstrap:
    initdb:
      database: {{ .Values.databaseName }}
      owner: {{ .Values.databaseUserName }}
      secret:
        name: my-postgres-secret
