apiVersion: v1
kind: Secret
metadata:
  name: {{ include "titeenipeli.name" . }}-secret
  labels:
    {{- include "titeenipeli.labels" . | nindent 4 }}
type: Opaque
data:
  bot-token: {{ .Values.botToken | b64enc }}
  jwt-secert: {{ .Values.jwtSecret | b64enc }}
  jwt-encryption: {{ .Values.jwtEncryption | b64enc }}
  tg-token: {{ .Values.tgToken | b64enc }}