apiVersion: v1
kind: Service
metadata:
  name: {{ include "titeenipeli.frontendName" . }}
  labels: {{- include "titeenipeli.frontendLabels" . | indent 4 }}
spec:
  ports:
    - name: http
      port: 80
      protocol: tcp
      targetport: http
  selector: {{- include "titeenipeli.frontendSelectorLabels" . | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "titeenipeli.backendName" . }}
  labels: {{- include "titeenipeli.backendLabels" . | indent 4 }}
spec:
  ports:
    - name: https
      port: 443
      protocol: tcp
      targetport: https
  selector: {{- include "titeenipeli.backendSelectorLabels" . | indent 4 }}