apiVersion: v1
kind: Service
metadata:
  name: {{ include "titeenipeli.frontendName" . }}
  labels: {{- include "titeenipeli.frontendLabels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetport: http
  selector: {{- include "titeenipeli.frontendSelectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "titeenipeli.backendName" . }}
  labels: {{- include "titeenipeli.backendLabels" . | nindent 4 }}
spec:
  ports:
    - name: https-off
      port: 8443
      protocol: TCP
      targetport: 8443
    - name: http
      port: 8080
      protocol: TCP
      targetport: 8080
  selector: {{- include "titeenipeli.backendSelectorLabels" . | nindent 4 }}