apiVersion: v1
kind: Pod
metadata:
  name: busybox-env
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "env && sleep 3600"]
      env:
        - name: EXAMPLE_VAR
          value: "Hello, Kubernetes!"
        - name: SECRET_PART1
          value: "test"
        - name: SECRET_PART2
          value: "too"
        - name: COMBINED_SECRET
          value: "$(SECRET_PART1)$(SECRET_PART2)"
  restartPolicy: Never
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-with-metrics
spec:
  instances: 3

  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: true
