apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-dashboard-auth
spec:
  basicAuth:
    secret: traefik-dashboard-auth-secret
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ratelimit-player
  namespace: titeenipeli
spec:
  rateLimit:
    average: 10
    burst: 15
    period: 10s
    sourceCriterion:
      requestHeaderName: "cookie"
