apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-dashboard-auth
spec:
  basicAuth:
    secret: traefik-dashboard-auth-secret
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ratelimit-player
  namespace: titeenipeli
spec:
  rateLimit:
    average: 20
    burst: 25
    period: 1m
    sourceCriterion:
      requestHeaderName: "cookie"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ipwhitelist
  namespace: titeenipeli
spec:
  ipWhiteList:
    sourceRange:
      - 192.168.0.1
