enabled: true
kubeControllerManager:
  enabled: true
nodeExporter:
  enabled: true
defaultRules:
  create: true
  rules:
    k8s: true
    kubelet: true
    node: true
    nodeExporterRecording: true
    alertmanager: false
    etcd: false
    configReloaders: false
    general: false
    kubeApiserver: false
    kubeApiserverAvailability: false
    kubeApiserverSlos: false
    kubeProxy: false
    kubePrometheusGeneral: false
    kubePrometheusNodeRecording: false
    kubernetesApps: false
    kubernetesResources: false
    kubernetesStorage: false
    kubernetesSystem: false
    kubeScheduler: false
    kubeStateMetrics: false
    network: false
    nodeExporterAlerting: false
    prometheus: false
    prometheusOperator: false
prometheus:
  prometheusSpec:
    remoteWrite:
      - url: "http://lgtm-distributed-mimir-nginx.monitoring.svc:80/api/v1/push"
    externalLabels:
      environment: "mimir"
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector:
      matchLabels:
        prometheus: "watch"
grafana:
  enabled: false
alertmanager:
  enabled: false
