apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
  namespace : cert-manager
spec:
  secretName: wildcard
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: '{{ .Values.hostedZoneName }}'
  dnsNames:
  - "{{ .Values.hostedZoneName }}"
  - "*.{{ .Values.hostedZoneName }}"