apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls
  namespace: traefik
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "{{ .Values.hostedZoneName }}"
  dnsNames:
    - "{{ .Values.hostedZoneName }}"
    - "*.{{ .Values.hostedZoneName }}"
