secretsprovider: azurekeyvault://pulumititeenipeli.vault.azure.net/keys/infra
encryptedkey: c3hKdUtXUzJ4QjdiZ2Q2VDI4QV8xbl9DdWtGamtGMU5XWmlMWmhDX0Vramx3ZjlzNnFuREhWNU1rS0hVeFJEZ0NHQ3p0MHBIVE10YXBNSUE4ZW9yT0JVdy1QZHRxWDdJRG4wNk5jYkt5OU5qQk1IemMtUEU0dmZyLXNoNVp3TFBQTzRHeEhfai1PeGEybnh5cUdidng2U1ZWTHdwdWJxMV9wY3gwbHJZQ3ktQkVrdDdWQWVWbjVBZW1wSTkzNHJFNWstX3dFT2M1UXhJQWotcmRVOGpEOVMzamw2dmlEXzdxMnI1Y3hNbGZTOWJTS2FpcnRWNm1DekxFa0VlalJMWFpEUDVtQ29scTlBSjlTT19YTUU1ak84QXhRMTBLa2VpeGhWMDVRbnV4Z1VvczU5OUlNVGVGSUlJMHo0ZGZSWldUMzJxVUIyNmU2cUhkNWFUdEZMa29R
config:
  azure-native:location: swedencentral
