services:
  titeenipeli:
    image: titeenipeli:latest
    build:
      context: .
      dockerfile: backend/Titeenipeli/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - JWT__Secret=${JWT_SECRET}
      - JWT__Encryption=${JWT_ENCRYPTION}
      - SQLCONNSTR_Database=Server=db;Port=5432;Userid=${POSTGRES_USER};Timeout=15;Database=${POSTGRES_DB};Password=${POSTGRES_PASSWORD};
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432