secretsprovider: azurekeyvault://titeenipelifoundation.vault.azure.net/keys/kube
encryptedkey: Q2cxTEo4YWt4QU1VeWVCeHVTcFRkalY2QlJxeEdBRDRKN1psekRKdFZ5XzBwTzN3bXRSYUpqY3NzUFQ1N2VpbTdoUkxscWJZV3VkdEVTeHdXR2F3VTJhVERxUWM5WE9OMUJycDR0T2RsR0g5Wk4yRzluNEhISGFtamZPUVhTc3QxZU9XMUoxVm5NTEpsNFVQNGhxWVQ2alJTbUFGMWlwTU1lOU85VEpqT01GM3FCUFRreThyUE9ZR0xuMXdLX1hTX1p2LUdtaHZWOGRkc3hnYzdOTW1PbkM2cFdqYVhUcDc3d2NiWEdvRGliMGU1Z2ZTdkxNbGRqel9UWUItU1c3QUJzUXpmLW5IWlN5R2FHeU5oWmxsUWxYTjd1VENDRmJjWjZZLUI0SnlZQ002bWVPVEt5Y2Q0dmc0VnlIbGk4WG9QYXpqdkpJM2JqZ0FBWVFybkttUnRn
config:
  azure-native:location: swedencentral
  titeenipelikube:email:
    secure: v1:acKXqXxhvb0uVRxA:Zy9aQC3D3I4YMyqdE1B5KJPp8E/lCNa1KzZLuuYi0Hl/YWtCsGqO
