name: Run dotnet lint on backend
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "src/backend/**"
    branches:
      - main

env:
  dotnet-version: "8.0.x"

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet-version }}

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          dotnet_format: true
          dotnet_format_dir: src/backend/
