name: Build docker images
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
  pull_request:
    paths:
      - "src/**"
    branches:
      - main

env:
  acr_name: titeenipelitacr.azurecr.io

jobs:
  docker:
    name: Run build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.acr_name }}
          username: ${{ secrets.AZURE_SP_ACR_CLIENT_ID }}
          password: ${{ secrets.AZURE_SP_ACR_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test build frontend
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: ./src/
          file: ./src/frontend/Dockerfile
          push: true
          tags: frontend:latest

      - name: Test build backend
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: ./src/
          file: ./src/backend/Titeenipeli/Dockerfile
          push: true
          tags: titeenipeli:latest

      - name: Test build titeenipeli bot
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: ./src/backend
          file: ./src/backend/Titeenipeli.Bot/Dockerfile
          push: true
          tags: titeenipeli.bot:latest

      - name: Build and push backend
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: ./src/
          file: ./src/backend/Titeenipeli/Dockerfile
          push: true
          tags: titeenipeli:latest

      - name: Build and push frontend
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: ./src/
          file: ./src/frontend/Dockerfile
          push: true
          tags: frontend:latest

      - name: Build and push titeenipeli bot
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: ./src/backend
          file: ./src/backend/Titeenipeli.Bot/Dockerfile
          push: true
          tags: titeenipeli.bot:latest

      - name: Purge old images only keep 3 newest
        if: github.ref == 'refs/heads/main'
        run: |
          acr purge \
              --registry ${{env.acr_name }} \
              --filter ".*:.*" \
              --keep 3
