name: Pulumi kube preview
on:
  pull_request:
    paths:
      - "infra/pulumi/kube/**"
    branches:
      - main

env:
  working-dir: ./infra/pulumi/kube
  go-version: "1.22"
  stack-name: dev
  cloud-url: azblob://iacstate?storage_account=${{ secrets.AZURE_BLOB_ACCOUNT }}

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    environment: plan
    if: github.ref != 'refs/heads/main'
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.working-dir }}
    steps:
      - name: Az CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Go ✨
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
          cache-dependency-path: ${{ env.working-dir }}/go.sum

      - name: Downloading dependencies 📦
        run: go mod download

      - name: Preview infrastructure 🚀
        uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: ${{ env.stack-name }}
          cloud-url: ${{ env.cloud-url }}
          work-dir: ${{ env.working-dir }}
          comment-on-pr: true
          comment-on-summary: true
          diff: false
        env:
          ARM_USE_MSI: true
