name: Pulumi
on:
  push:
    paths:
      - "infra/**"
    branches:
      - main
  pull_request:
    paths:
      - "infra/**"
    branches:
      - main

env:
  working-dir: ./infra/test

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    environment: plan
    defaults:
        run:
          shell: bash
          working-directory: ${{ env.working-dir }}
    steps:
      - name: Az CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Go ✨
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Downloading dependencies 📦
        run: go mod download

      - name: Applying infrastructure 🚀
        uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: titeeni/peli
          cloud-url: ${{ secrets.AZURE_BLOB_ACCOUNT }}
          work-dir: ${{ env.working-dir }}
