openapi: "3.1.0"
info:
  description: "Titeenipeli 25 API specification"
  version: "0.0.1"
  title: "Titeenipeli 25 API"
  contact:
    email: "viesti@roni-juntunen.fi"
  license:
    name: "Unlicense"
    url: "https://unlicense.org/"
servers:
  - url: https://{domain}:{port}/api/{version}
    variables:
      domain:
        default: pixel-hunt
        description: Example server
      port:
        enum:
          - "8443"
          - "443"
        default: "443"
      version:
        enum:
          - "v1"
        default: "v1"
tags:
  - name: "ctf"
    description: "Everything related to Capture The Flag (CTF) tokens."
  - name: "state"
    description: "Endpoint for interacting with game state."
  - name: "users"
    description: "Endpoint for interacting with users"

paths:
  /ctf:
    $ref: "./paths/ctf.yaml"
  /state/map/pixels:
    $ref: "./paths/state/map/pixels.yaml"
  /state/game:
    $ref: "./paths/state/gameState.yaml"
  /state/powerups/activate:
    $ref: "./paths/state/powerups.yaml"
  /users/authenticate:
    $ref: "./paths/users/authenticate.yaml"

components:
  securitySchemes:
    bearerAuth:
      $ref: "./components/securitySchemas/bearerAuth.yaml"
    botAuth:
      $ref: "./components/securitySchemas/botAuth.yaml"
